### ISSUE TITLE
Not react-only ready

### ISSUE THREAD

**Issue by hunter-koppen** [ahwelgemoed/lottie-mendix-widget#2]
I get the following error in react-only mode in Mx10:

Please make sure the following pluggable widgets are updated to the latest version available in the marketplace.
If you own any of these widgets, please check if they were generated using the latest version of pluggable-widgets-tools and are ES6 modules:
 • Lottiemendixwidget (mendix-lottiemendixwidget)

**Comment by ahwelgemoed** [comment]
@hunter-koppen - Dag, I no longer work on or for Mendix. Sorry.
